[application]
name = "Chrysocolle"

[bundle]
identifier = "com.Probbes.app"
publisher = "Probbes"
category = "Utility"
short_description = "A emulator manager that sync save files to github"
icon = ["assets/icon.ico", "assets/Chrysocolle.png"]

[desktop]